SuperGroup:
  Level:
    1:
      contribution: 500000
      Day: 5
      Number: 5
      LevelUpcontribution: 500000
    2:
      contribution: 1000000
      Day: 10
      Number: 6
      LevelUpcontribution: 3000000
    3:
      contribution: 4000000
      Day: 20
      Number: 7
      LevelUpcontribution: 8000000
    4:
      contribution: 12000000
      Day: 30
      Number: 8
      LevelUpcontribution: 22000000
    5:
      contribution:  32000000
      Day: 50
      Number: 9
      LevelUpcontribution: 62000000
    6:
      contribution: 94000000
      Day: 80
      Number: 10
      LevelUpcontribution: 100000000
    7:
      contribution: 180000000
      Day: 100
      Number: 15
      LevelUpcontribution: 480000000
    8:
      contribution: 580000000
      Day: 120
      Number: 20
      LevelUpcontribution: 580000000
    9:
      contribution: 2300000000
      Day: 150
      Number: 25
      LevelUpcontribution: 999999999
  VicePresidentNum: 2
  EliteNum: 3
  GroupCardLore: CanCreateGroup
  Donation: 100000-50000-1000000
  GroupShopTitle: '§c§l工会的商城'
  GroupShop:
    1:
      ID: '95-1'
      DisPlayName: '§d§l为是名字0'
      Lore: '§c§l这个是爱迪生-§d§l我是第二行内容-价格:[MustContribution]'
      MustContribution: 154400
      DoCmd: give [Player] 64 1
    2:
      ID: '15'
      DisPlayName: '§d§l为是名字1'
      Lore: '§c§l这个是爱迪生-§d§l我是第二行内容-§d§l价格:[MustContribution]'
      MustContribution: 150650
      DoCmd: give [Player] 64 1
    3:
      ID: '35'
      DisPlayName: '§d§l为是名字2'
      Lore: '§c§l这个是爱迪生-§d§l我是第二行内容-§d§l价格:[MustContribution]'
      MustContribution: 15050
      DoCmd: give [Player] 64 1
    4:
      ID: '95-6'
      DisPlayName: '§d§l为是名字5'
      Lore: '§c§l这个是爱迪生-§d§l我是第二行内容-§d§l价格:[MustContribution]'
      MustContribution: 15000
      DoCmd: give [Player] 64 1
  Lang:
    SuperGroupInfo:
      - §4=======SuperGroup=======
      - §41.[任何人]查看服务器公会列表/SG list
      - §42.[任何人]查看自己公会/SG SG
      - §43.[任何人]创建公会/SG create 公会名
    SuperGroupListTitle: §d公会列表
    PlayerItem:
      - 玩家名:[Player]
      - 玩家贡献点:[Contribution]
      - 玩家职位:[Postion]
      - 玩家UUid:[UUID]
    SGlistItem:
      - 公会名:[SuperGroupName]
      - 公会等级:[SuperGroupLevel]
      - 人数:[SuperGroupHumanNum]
      - 会长:[oderName]
      - 编号:[GroupKeyId]
    PageUpButtonDisPlay: 上一页
    PageDownButtonDisPlay: 下一页
    PlayerListViewTitle: 工会玩家列表
    GroupMenuTitle: 公会主菜单
    ContributionTitle: 捐献页面
    PlayerOperationTitle: §c§l玩家操作台