SuperGroup:
  Level:
    1:
      contribution: 500
      Day: 5
      Number: 5
    2:
      contribution: 1000
      Day: 10
      Number: 6
    3:
      contribution: 2000
      Day: 20
      Number: 7
    4:
      contribution: 2500
      Day: 30
      Number: 8
    5:
      contribution:  3000
      Day: 50
      Number: 9
    6:
      contribution: 3500
      Day: 80
      Number: 10
    7:
      contribution: 4000
      Day: 100
      Number: 15
    8:
      contribution: 5000
      Day: 120
      Number: 20
    9:
      contribution: 10000
      Day: 150
      Number: 25
  Vice_President: 2
  Elite: 3
  EnterGroupTimeSetPosition: 2
  GroupCardLore: CanCreateGroup
  Donation: 10000000-5000000-10000000
  Lang:
    SuperGroupInfo:
      - §4=======SuperGroup=======
      - §41.[任何人]查看服务器公会列表/SG list
      - §42.[任何人]查看自己公会/SG SG
      - §43.[任何人]创建公会/SG create 公会名
    SuperGroupListTitle: §d公会列表
    SGlistItem:
      - 公会名:[SuperGroupName]
      - 公会等级:[SuperGroupLevel]
      - 人数:[SuperGroupHumanNum]
      - 会长:[oderName]
      - 编号:[GroupKeyId]
    PageUpButtonDisPlay: 上一页
    PageDownButtonDisPlay: 下一页
    PlayerListViewTitle: 工会玩家列表
    GroupMenuTitle: 公会主菜单
    ContributionTitle: 捐献页面