SuperGroup:
  Level:
    1:
      contribution: 500000
      Day: 5
      Number: 5
      LevelUpcontribution: 500000
    2:
      contribution: 1000000
      Day: 10
      Number: 6
      LevelUpcontribution: 3000000
    3:
      contribution: 4000000
      Day: 20
      Number: 7
      LevelUpcontribution: 8000000
    4:
      contribution: 12000000
      Day: 30
      Number: 8
      LevelUpcontribution: 22000000
    5:
      contribution:  32000000
      Day: 50
      Number: 9
      LevelUpcontribution: 62000000
    6:
      contribution: 94000000
      Day: 80
      Number: 10
      LevelUpcontribution: 100000000
    7:
      contribution: 180000000
      Day: 100
      Number: 15
      LevelUpcontribution: 480000000
    8:
      contribution: 580000000
      Day: 120
      Number: 20
      LevelUpcontribution: 580000000
    9:
      contribution: 2300000000
      Day: 150
      Number: 25
      LevelUpcontribution: 999999999
  Vice_President: 2
  Elite: 3
  EnterGroupTimeSetPosition: 2
  GroupCardLore: CanCreateGroup
  Donation: 100000-50000-1000000
  Lang:
    SuperGroupInfo:
      - §4=======SuperGroup=======
      - §41.[任何人]查看服务器公会列表/SG list
      - §42.[任何人]查看自己公会/SG SG
      - §43.[任何人]创建公会/SG create 公会名
    SuperGroupListTitle: §d公会列表
    SGlistItem:
      - 公会名:[SuperGroupName]
      - 公会等级:[SuperGroupLevel]
      - 人数:[SuperGroupHumanNum]
      - 会长:[oderName]
      - 编号:[GroupKeyId]
    PageUpButtonDisPlay: 上一页
    PageDownButtonDisPlay: 下一页
    PlayerListViewTitle: 工会玩家列表
    GroupMenuTitle: 公会主菜单
    ContributionTitle: 捐献页面